#validation
framework:
  carValidation:
    returnOnStepError: false
    canBeMultiThreaded: true
    validationCommands:
      - description: Type
        inParallel: true
        validations:
          basic:
            type: String
            format: '^[a-zA-Z0-9 -]+'
          custom:
            - null

      - description: Make
        inParallel: true
        validations:
          basic:
            type: String
            format: '^[a-zA-Z0-9 -]+'
          custom:
            - null

      - description: Model
        inParallel: true
        validations:
          basic:
            type: String
            format: '^[a-zA-Z0-9 -]+'
          custom:
            - null

      - description: Trim
        inParallel: true
        validations:
          basic:
            type: String
            format: '^[a-zA-Z0-9 -]+'
          custom:
            - null

      - description: Year
        inParallel: true
        validations:
          basic:
            type: Integer
            format: '[0-9]{4}'
          custom:
            - null

      - description: StreetSave
        inParallel: true
        validations:
          basic:
            type: Boolean
            format: '(\bYES\b|\bNO\b|\bTRUE\b|\bFALSE\b){1}'
          custom:
            - null

      - description: Electric
        inParallel: true
        validations:
          basic:
            type: Boolean
            format: '(\bYES\b|\bNO\b|\bTRUE\b|\bFALSE\b){1}'
          custom:
            - 'VERIFY_ELECTRIC'

      - description: Range
        inParallel: true
        validations:
          basic:
            type: Integer
            format: '[0-9]{1,8}'
          custom:
            - null